input_info:
  - bin_path: ./000000397133.bin
    shape: (1, 3, 300, 300)
    dtype: np.float32
    input_name: input
om_path: ./ssd_bs1.om
onnx_path: ./ssd_part.onnx
dump_save_path: ./res
npu_device_id: 1
msame_path: ./msame/x86/msame
msaccucmp_py_path: /usr/local/Ascend/ascend-toolkit/latest/x86_64-linux/toolkit/tools/operator_cmp/compare/msaccucmp.py
env: |
  export install_path=/usr/local/Ascend/ascend-toolkit/latest
  export PATH=/usr/local/python3.7.5/bin:${install_path}/atc/ccec_compiler/bin:${install_path}/atc/bin:$PATH
  export PYTHONPATH=${install_path}/atc/python/site-packages:$PYTHONPATH
  export LD_LIBRARY_PATH=${install_path}/atc/lib64:${install_path}/acllib/lib64:$LD_LIBRARY_PATH
  export ASCEND_OPP_PATH=${install_path}/opp
